source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'erubis'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'sinatra'
gem 'unicorn'
gem 'rack-lineprof'
gem 'rack-mini-profiler'
gem 'pry-byebug'
gem 'redis', '3.3.1'


group :development do
  gem 'foreman'
  gem 'sinatra-contrib', require: nil
end
